### ISSUE TITLE
Una gatita llora cada vez que...

### ISSUE THREAD

**Issue by nasivuela** [Adalab/d-s1-evaluacion-intermedia-mariavioleta1417#3]
A indentar ese código! Evita las lineas vacias dentro de las reglas de css.

![](https://media.giphy.com/media/71PLYtZUiPRg4/giphy.gif)

**Comment by nasivuela** [comment]
Reabro esta, que parece que se nos ha ido la mano indentado en el css ;D
Solo cuando una regla está dentro de otra (como en sass) tenemos que aumentar la indentación, si dos reglas están alado su indentación es del mismo nivel.

Indentación chungui:
```css
.header {
  background-color: green;
}

  .main {
    background-color: black;
  }
```

Indentación chachi:
```css
.header {
  background-color: green;
}

.main {
  background-color: black;
}
```
